name: Game of life testing

on: push

jobs:
  game-of-life-test:
    runs-on: ${{ matrix.os }}
    strategy:
     fail-fast: false
     matrix:
        java: [ '11', '14' ]
        os: [ubuntu-latest, windows-latest]
        experimental: [false] 
        include:
          - java: 17
            os: ubuntu-latest
            experimental: true
            continue-on-error: true
    steps:
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.5.4
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Java version
        run: java -version
      - name: Maven version
        run: mvn --version
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Maven test
        run: mvn test

